name: ☁️ New Fleet instance
description: Create a new Fleet instance for a prospect
title: "New Fleet instance: ___________________.cloud.fleetdm.com"
labels: ":help-customers"
body:
  - type: input
    id: instance_url
    attributes:
      label: Instance URL
      placeholder: ie. acme.cloud.fleetdm.com
    validations:
      required: true
  - type: input
    id: org_display_name
    attributes:
      label: Organization display name
      placeholder: ie. Acme Co.
    validations:
      required: true
  - type: dropdown
    id: aws_region
    attributes:
      label: AWS Region
      options:
        - us-east-2
        - eu-central-1
        - ap-south-1
      default: 0
    validations:
      required: true
  - type: input
    id: fleet_license_key
    attributes:
      label: Fleet license key
    validations:
      required: true
  - type: input
    id: number_of_hosts
    attributes:
      label: Number of hosts
    validations:
      required: true
