name: ☁️ New Fleet instance
description: Create a new Fleet instance for a prospect
title: "New Fleet instance: ___________________.cloud.fleetdm.com"
labels: [":help-customers"]
body:
  - type: input
    id: instance_url
    attributes:
      label: Instance URL
      placeholder: ie. acme.cloud.fleetdm.com
    validations:
      required: true
  - type: input
    id: org_display_name
    attributes:
      label: Organization display name
      placeholder: ie. Acme Co.
    validations:
      required: true
  - type: dropdown
    id: aws_region
    attributes:
      label: AWS Region
      options:
        - us-east-2
        - eu-central-1
        - ap-south-1
      default: 0
    validations:
      required: true
  - type: input
    id: fleet_license_key
    attributes:
      label: Fleet license key
    validations:
      required: true
  - type: input
    id: number_of_hosts
    attributes:
      label: Number of hosts
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## This section is for the infrastructure team
        - [ ] Configure `FLEET_MDM_SSO_RATE_LIMIT_PER_MINUTE` based on host count above:
        - [ ] Set up requested subdomain based on the title of this issue. Ensure subdomain looks conventional. Conventional subdomains are all lowercase and use dashes (e.g. `foo-bar-inc.cloud.fleetdm.com`).
        - [ ] Set up Fleet instance.
        - [ ] Test that domain actually works.
        - [ ] Do all configuration, including the license key.
        - [ ] Add global admin credentials to Customer-PoV vault.
        - [ ] Post in #help-infra and tag original requestor that the instance has been created
