name: ☁️ New Fleet instance
description: Create a new Fleet instance for a prospect
title: "New Fleet instance: ___________________.cloud.fleetdm.com"
labels: ":help-customers"
body:
  - type: input
    id: domain_url
    attributes:
      label: Domain URL
      placeholder: ex. acme.cloud.fleetdm.com
    validations:
      required: true
  - type: input
    id: org_display_name
    attributes:
      label: Organization display name
      value: "Acme Co."
    validations:
      required: true
  - type: dropdown
    id: aws_region
    attributes:
      label: AWS Region
      options:
        - us-east-2
        - eu-central-1
        - ap-south-1
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
